# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapboxAccuTerraDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxAccuTerraDemo
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
end
